name: CODE-BUILD

on:
  workflow_dispatch:
    inputs:
      Release_Check:
        type: boolean
        description: Release this Build
        required: true

jobs:
  Pre-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check-out Templates
        run: |
          echo checking out templates!!
      - name: Pre-Release Task
        run: echo updating Version Repo!!
        
      - name: Set Release Version
        run: echo setting release version!!
        
      - name: Pre-Build
        run: |
          echo Executing Pre build steps!!

      - name: Build and Security Test
        run: |
          echo Build and security testing!!

      - name: Build and Sonar Analysis
        run: |
          echo Starting Build+Sonar!!

  Build-Sonar:
    needs: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Malavika1113_Demo-Github-Migration
  Fortify:
    needs: Pre-Release
    runs-on: ubuntu-latest
    steps:    
      - name: Fortify Analysis
        run: |
          echo Starting Fortify stage!!

  Upload:
    if: ${{ github.event.inputs.Release_Check }}
    needs: [Build-Sonar,Fortify]
    runs-on: ubuntu-latest
    steps:      
      - name: Upload to Nexus
        run: |
          echo Uploading Artifacts to Nexus!!

  Post-Release:
    needs: [Upload]
    runs-on: ubuntu-latest
    steps:    
      - name: Post Release Task
        run: |
          echo Update Versioning Repo!!

  Declarative-Post-Actions:
    needs: [Post-Release]
    runs-on: ubuntu-latest
    steps:    
      - name: Sent Results
        run: echo Mailing results to recipients!!
