name: GitHub Runner

on: 
  workflow_dispatch:

jobs:
#   Start-aws-ec2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Start EC2
#         run: |
#           aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }} 
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
#   Sleep-ec2:
#     needs: Start-aws-ec2
#     runs-on: ubuntu-latest
#     steps:
#       - name: Waiting EC2 to Start
#         run: |
#           sleep 60
          
  Check-ec2-Status:
    #needs: Sleep-ec2
    runs-on: ubuntu-latest
    #outputs:
      #my-key: ${{ steps.mykey.outputs.defined }}
    steps:
      - name: Checking status of EC2
        id: statusCheck
        run: |
          status=$( aws ec2 describe-instance-status --instance-id ${{secrets.AWS_EC2_INSTANCE_ID }} | jq -r '.InstanceStatuses[] | .InstanceState | .Name' )
          echo "::set-output name=OUTPUT::$status"
      - name: ABC
        if: steps.statusCheck.outputs.OUTPUT != "running"
        run: exit 1
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
           
  test:
      runs-on: ubuntu-latest
      needs: Check-ec2-Status
      steps:
       - run: echo ${{needs.Check-ec2-Status.outputs.mykey}}
   
           
#   Build:
#     needs: Check-ec2-Status
#     runs-on: self-hosted
#     steps:
#       - name: Build ECOMM
#         run: |
#           echo "Hello world"
          
#   Stop-aws-ec2:
#     needs: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Stop EC2
#         run: |
#           aws ec2 stop-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
          
